### PR TITLE
Add newsletter

### PR DESCRIPTION
**Pull request by duje**

### CODE REVIEW

**Comment by HarelM** [comment]
Regarding maplibre-gl:
3.1 was releases with the support of webgl 1 back.
Not sure if the newsletter mentioned the release of 3.0 since it happened a month ago...
Can't think of anything else worth mentioning ATM.

**Comment by louwers** [comment]
@HarelM Yes there was a separate post on that.

@duje For Web let's link to https://maplibre.org/news/2023-05-23-maplibre-gl-js-v3/ and also mention that 3.1 has been released in the meantime. :)

**Comment by louwers** [comment]
I would add a Sponsor announcement on top like in previous months.

Also I would go with order Highlights (with sponsor message) -> MapLibre Native Bounties-> MapLibre GL JS(since the update is so small, and also for consistency)

1. It's 'Martin' not MapLibre Martin.
2. Should we create a separate news article for that like with maplibre-rs?

**Review by louwers — CHANGES_REQUESTED** [review]
See comment above.

**Comment by duje** [comment]
@nyurik asked me to add Martin to the newsletter, and so did @HarelM with GL JS above. Even though this time Bounties are about Native only, I would keep it as a general heading as they will always appear in some way or another to encourage people to work on the directions, no matter what repo. The announcement has been made yesterday: https://maplibre.org/news/2023-06-22-jawgmaps-becomes-a-maplibre-silver-sponsor/

**Comment by nyurik** [comment]
I prefer to keep everything in one newsletter to minimize noise. There are already individual release notifications. Newsletter should come out regularly (monthly), and include all maplibre news, not just one or two projects

**Review by louwers — APPROVED** [review]
Provisionally approved.

Please add a JawgMaps logo. Thanks Duje!

**Pull request merged**
