### PR TITLE
Add metal started announcement

### PR DESCRIPTION
**Pull request by wipfli**
Adds a small announcement about Metal.

CI probably fails because GitHub has issues with certificates.

### CODE REVIEW

**Comment by wipfli** [comment]
Ready for review

**Review by HarelM — APPROVED** [review]

**Comment by wipfli** [comment]
https://twitter.com/maplibre/status/1639571154854715392

**Comment by wipfli** [comment]
https://mastodon.social/@maplibre/110083409522880985

**Comment by wipfli** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:7045339313315684353

**Pull request merged**
