### PR TITLE
Refactored news handling

### LINKED ISSUE #358: Heading in overview
We updated Hugo, which fixed one issue, but I noticed that headings have started to show up on https://maplibre.org/news/

### PR DESCRIPTION
**Pull request by CommanderStorm**
I also touched a few of the other parts (i can remove those changes if you want ^^)

Resolves #358

here are a screenshots of the changed pages:

image
image
image

### CODE REVIEW

**Comment by HarelM** [comment]
Please make sure this looks good on mobile devices as well. Thanks!!

**Comment by CommanderStorm** [comment]
Good point.
I have tweaked the design slightly (adding non breaking spaces, reducing a bit of vertical spacing), but nothing major:

image
image
image

**Review by louwers — CHANGES_REQUESTED** [review]
Hey that's neat!!

Spaces should be added when there are two authors.

image

Also, I think I would like the category tags at the top of the article better instead of at the bottom.

**Comment by CommanderStorm** [comment]
Sorry about that bug, that was a last minute fix that I did not test properly apparently 😰
It looks like this now (what do you think?):

image
image

**Comment by louwers** [comment]
I am still not seeing any spaces for some reason.

**Comment by CommanderStorm** [comment]
Oops.
I will look into this in a few minutes when I'm off the train (the non braking space there would be pretty ugly in terms of overflow)

**Comment by louwers** [comment]
@CommanderStorm I had to add a nbsp and add a `-` to trim the whitespace in the Go template (otherwise the formatter would break it again).

**Review by louwers — APPROVED** [review]
Seems fixed now.

Thank you, looks great, will merge it later unless you still want to make a change. :)

**Comment by louwers** [comment]
One last thing, let's remove the 'x minutes read' so it's easier to fit on one line.

**Comment by CommanderStorm** [comment]
> unless you still want to make a change

I changed this to not be non-breaking spaces. This way, splits at all the red spaces are possible for the authors part:
image

**Comment by louwers** [comment]
Sorry, looking at the final result I think I like the current header better. Do you mind reverting it?

It's easier to skim over the authors (which is not super relevant information) when they are in the current button style.

**Comment by CommanderStorm** [comment]
Shure can revert it (which part of the news section? should I also keep the removed read timer) ^^

There are these alternatives
image

This would look like this:

**Comment by louwers** [comment]
I think I prefer it as it was before, including the read timer.

**Comment by CommanderStorm** [comment]
Have mostly reverted the changes (the changes that I kept to the page don't affect the design)

image

**Pull request merged**
