### PR TITLE
Landing page layout

### PR DESCRIPTION
**Pull request by birkskyum**
I've been looking into improving the website a bit, by making a more visual "projects"-page on the front-page, dark-mode design to make our logo and maps pop, fix some issues with responsiveness etc.

We really should be remaking this in something less Hugo anyway... that's the next step

Screenshot 2023-10-20 at 18 37 45

Screenshot 2023-10-20 at 18 38 05
Screenshot 2023-10-20 at 18 37 52

### CODE REVIEW

**Review by louwers — CHANGES_REQUESTED** [review]
I love it! BIG improvement, especially on mobile.

Also making the map its own thing and not just something in the background is a great choice.

Something I have noiticed is that there is an issue with line breaks within links. See the screenshots below.

Also, I think we should make use of `prefers-color-scheme`: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

If you want we can have a dark color scheme by default, but I would personally prefer to also have a light option

```css
}
@media (prefers-color-scheme: light) {
  ...
}
```

## Line Breaking Issue






## Difference on Mobile ❤️

**Comment by louwers** [comment]
Added the new Twitter logo here to avoid a merge conflict.

**Comment by birkskyum** [comment]
Nice, i increased badge size, and removed the line-breaks from the links.

**Comment by birkskyum** [comment]
Regarding the light/dark style. I'd be happy to make proper modes like that, and have done it on other sites, but I'd prefer to do it when we swap hugo/bootstrap.

**Comment by nyurik** [comment]
want to make board members appear in random order too? Would be nice :)

**Comment by birkskyum** [comment]
> want to make board members appear in random order too? Would be nice :)

Great idea - think we got something like that in the community map. It's static site generation, so it'll randomize for each new commit, not each page reload.

**Comment by birkskyum** [comment]
@nyurik , it's shuffling now.

**Comment by nyurik** [comment]
I think it should be fairly easy to do in javascript too - it would work even with static page gen, on load would simply shuffle a few html DIVs?

**Comment by birkskyum** [comment]
> I think it should be fairly easy to do in javascript too - it would work even with static page gen, on load would simply shuffle a few html DIVs?

sure, if you'd prefer that rather than per commit, feel free to make a pr. Otherwise, it'll be in the backlog for when we rebuild in typescript.

**Review by nyurik — APPROVED** [review]
amazing job!

**Pull request merged**
