### PR TITLE
Remove maputnik

### PR DESCRIPTION
**Pull request by birkskyum**
#265 

Before
Screenshot 2023-10-29 at 02 09 18

After

Screenshot 2023-10-29 at 01 20 27

### CODE REVIEW

**Comment by nyurik** [comment]
I would keep it. Just like a ref mb specs like mvt, we should link and promote style editing

**Comment by birkskyum** [comment]
Sure - I'll leave it to someone else to champion this change if they desire.

**Comment by wipfli** [comment]
I agree that we should link to some style editor from our documentation website @nyurik. But at the moment it looks like maputnik is a maplibre project and it takes a very prominent place on our website, which I think is not accurate.

**Review by wipfli — APPROVED** [review]

**Comment by wipfli** [comment]
Thanks for the pull request @birkskyum!

**Comment by birkskyum** [comment]
@wipfli please don't self merge.

**Pull request merged**
