### PR TITLE
Fix sponsorship link

### PR DESCRIPTION
**Pull request by wipfli**
Sorry I used the wrong link for the sponsorship slide deck. Should be fixed here.

### CODE REVIEW

**Comment by birkskyum** [comment]
Something funky it also going on with this image Of Bart, because it doesn't shrink to small screens

**Comment by birkskyum** [comment]
[image]()

**Comment by wipfli** [comment]
I used a max width there

**Comment by birkskyum** [comment]
> I used a max width there

Also adding `width: 100%;` would probably solve it for the mobile case too.

**Review by birkskyum — APPROVED** [review]

**Pull request merged**
