### PR TITLE
Add roadmap

### PR DESCRIPTION
**Pull request by wipfli**
This adds the files which are up to now at https://roadmap.maplibre.org to the main project website https://maplibre.org/roadmap as static assets.

I still need to add the new Bounty Directions. And there is a bug with "Roadmap" appearing 2 times in the header.

@maxammann can you have a look at my probably completely horrible way of using hugo?

### CODE REVIEW

**Comment by wipfli** [comment]
Will look something like this:

image

**Comment by wipfli** [comment]
The double appearing "Roadmap" is fixed now. I just had to remove the `menu: []` in the Front Matter.

**Comment by wipfli** [comment]
Ready for review

**Review by birkskyum — APPROVED** [review]
Awesome!

**Review by lseelenbinder — APPROVED** [review]

**Comment by maxammann** [comment]
I'll find some time over the weekend! :)

**Pull request merged**
