### PR TITLE
list community info on the community page

### PR DESCRIPTION
**Pull request by pdebruic**
for  #153

### CODE REVIEW

**Comment by HarelM** [comment]
THANKS! can you share a screen shot of brefore/after?

**Comment by pdebruic** [comment]
## new community page 
new-com
## old community page 
old-com
## new about page 
new-about
## old about page 
old-about

**Comment by wipfli** [comment]
Thanks for improving this, @pdebruic. Please run `npm run format` to get the formatting right...

**Comment by maxammann** [comment]
Looks good!

**Review by HarelM — APPROVED** [review]

**Comment by pdebruic** [comment]
ok formatted.

**Comment by HarelM** [comment]
THANKS!

**Comment by pdebruic** [comment]
You're welcome.  Hope it helps

**Pull request merged**
