### PR TITLE
Make basked same color as balloon

### PR DESCRIPTION
**Pull request by birkskyum**
Make basked same color as balloon, to improve the order of focus and reduce blooming in dark mode.

### CODE REVIEW

**Comment by wipfli** [comment]
Thanks for opening this pull request. Before we merge it, I would like to discuss what our logo should be. Then we decide and then we publish it everywhere. The logo is not something we should be changing frequently.

For the brand identity, I think the two colors of the text with "Map" and "Libre" is an important feature of the old logo and we should keep it. Also the old colors are what people recognize and we should keep it.

If the main worry with the old logo is the shape of the map pin, then let's just change that shape and leave the rest as is...

**Comment by birkskyum** [comment]
This has nothing to do with the shape or the split text.

**Comment by nyurik** [comment]
@birkskyum my apologies if i missed the design discussion.  Sadly, we use too many venues for various discussions (github, slack, figma(?), ...?)  TBH, I am not too thrilled by this change - the two color (white and light blue) icons seem a bit better to me. Let's do any significant design changes like this only after proper community proposals - I know it sucks and slows down a lot of things, but logos/imagery is our face, and we should have a wider discussion before accepting.

**Comment by nyurik** [comment]
P.S. I am also a bit surprised we got rid of the two-color `MapLibre` (with "Map" being in one color, and "Libre" in another) - was it discussed/proposed anywhere?

**Comment by birkskyum** [comment]
https://github.com/maplibre/internal/issues/82#issuecomment-1793582716

**Pull request closed without merging**
