### PR TITLE
Announce second feedback round for bounties

### PR DESCRIPTION
**Pull request by wipfli**
News announcement for inviting people to give feedback on bounty allocation.

tweet/linkedin would be "We are happy to invite you to a second round of voting on Bounty directions. Please let us know which features would be helpful for you and upvote existing suggestions."

### CODE REVIEW

**Review by louwers — COMMENTED** [review]
The announcement looks fine but I think the Step-by-Step guide that is linked should be imporved. In praticular the structure of the document is quite confusing.

 I suggest:

- [ ] Including the monetary value of the two new sizes?
- [ ] Adding a section 'Join the developer pool'
- [ ] Adding a section 'Working on a bounty'
- [ ] Adding a sub-section 'Finding a bounty'
- [ ] Adding a sub-section 'Suggesting a bounty'
- [ ] Adding a sub-section 'Suggesting an epic'
- [ ] Adding a section 'Claiming a bounty'


I think the Step-by-step guide could also be improved.

**Comment by wipfli** [comment]
I agree the step-by-step guide is not good. Can you make a pull request to improve it?

**Review by louwers — APPROVED** [review]
Conditionally approved if #137 is merged first. 😉

**Comment by wipfli** [comment]
https://twitter.com/maplibre/status/1635558101330870273

**Comment by wipfli** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:7041324563783147520

**Comment by wipfli** [comment]
https://mastodon.social/@maplibre/110039372112747636

**Pull request merged**
