### PR TITLE
Add Slack link to own page

### PR DESCRIPTION
**Pull request by louwers**
It is easier to refer people to the Slack when it is on `maplibre.org/slack`.

### CODE REVIEW

**Review by HarelM — APPROVED** [review]

**Comment by wipfli** [comment]
Thanks for this suggestion @louwers. In the past we had some discussions that top level links (things after the /) should be used less to make the website less overloaded with too many tabs. This pull request goes a bit in this direction I think.

If we think about the website from the point of view of someone who is new to MapLibre, one question they might have is how do I interact with the community. The answer to this is that we use Slack, GitHub, and the monthly meetings for talking to each other. And we have the website, X, linkdin, and mastodon for news announcements. All of this info should be in one page in my opinion.

So should we maybe just rework maplibre.org/community and maybe add a slack logo there?

**Comment by louwers** [comment]
There should be an easy to remember link to direct people to our Slack. This is convenient on conferences.

To rework the community page with other ways to get involved is also a good idea, but we include those in our talk.

Since we link nowhere from this page from the website, I think it is fine to keep as it is. Maybe we can add it to robots.txt so it is not crawled.

**Comment by wipfli** [comment]
We are using the osmus slack, and they have the forwarding link https://slack.openstreetmap.us which I find very convenient already. I am worried that if we make our own version of this link then people will be confused that they get forwarded to the osmus slack...

**Comment by louwers** [comment]
They are not forwarded. They have to click and it is explained on the page. But I can use that link as well!

**Pull request merged**
