### PR TITLE
MapLibre React Native announcement

### PR DESCRIPTION
**Pull request by ianthetechie**
Announcement to finalize https://github.com/maplibre/maplibre/issues/134.

### CODE REVIEW

**Comment by wipfli** [comment]
Cool, looks good too me. I suggest the associated tweet will be:

> MapLibre has completed onboarding of [MapLibre React Native](https://github.com/maplibre/maplibre-react-native), an SDK that will make MapLibre GL Native more accessible to mobile developers.

**Comment by wipfli** [comment]
Thanks for writing this!

**Review by lseelenbinder — APPROVED** [review]

**Review by HarelM — APPROVED** [review]

**Comment by wipfli** [comment]
https://twitter.com/maplibre/status/1623269082958123008

**Comment by wipfli** [comment]
https://www.linkedin.com/posts/maplibre_reactnative-activity-7029035639006220288-9Mjv

**Pull request merged**
