### PR TITLE
Display Ukraine flag in MapLibre frontpage logo

### PR DESCRIPTION
**Pull request by wipfli**

### CODE REVIEW

**Comment by wipfli** [comment]
image

**Comment by HarelM** [comment]
While I think this is a valid cause, and I sympathise with the families and the Ukraine people, I don't think open source projects are the place for politics...

**Comment by nyurik** [comment]
@HarelM I agree there should be no politics. I disagree that this is politics, this is a statement of support for over a million refugees and non-stop bombing of the cities.  This is a statement to stop the war. Example:  https://leafletjs.com/

**Comment by jsanz** [comment]
QGIS is also supporting peace on their latest splash screens

https://twitter.com/Ginetto/status/1497155243410399232?t=ut8cJH40nA-fOXKMaUSzzA&s=19

**Pull request merged**
