### PR TITLE
Update about page

### PR DESCRIPTION
**Pull request by wipfli**
Update the about page.

@HarelM you might want to update your profile text and mention that you work in the the Maintainer Web role.

@louwers @ovivoda and myself need to write a motivation text roughly 2 paragrphs long stating why we work on MapLibre.

Can be merged as is and then we can update profile pages later.

### CODE REVIEW

**Comment by wipfli** [comment]
image

**Review by HarelM — APPROVED** [review]
LGTM

**Comment by louwers** [comment]
Having my name start with a `B` is paying dividends. :smile:

**Comment by ovivoda** [comment]
will do it this week and get back to you @wipfli !

**Pull request merged**
