### PR TITLE
Create news post about Maplibre Navigation V2

### PR DESCRIPTION
**Pull request by boldtrn**
This PR adds a news post about the latest release of Maplibre Navigation. Please let me know if you need any changes or if you are fine with this post.

### CODE REVIEW

**Review by wipfli — CHANGES_REQUESTED** [review]
Thanks for putting this together! Can you replace Maplibre with MapLibre? Then I will approve and merge...

**Comment by wipfli** [comment]
Ah and run npm run format...

**Comment by boldtrn** [comment]
Thanks for the review, I updated the spelling and ran format.

**Review by wipfli — APPROVED** [review]
Cool

**Comment by wipfli** [comment]
https://www.linkedin.com/posts/maplibre_navigation-android-activity-7046153642944405505-7C2U?utm_source=share&utm_medium=member_android

**Pull request merged**
