### PR TITLE
Revert commits after and including hugo migration

### PR DESCRIPTION
**Pull request by wipfli**
The docs website is currently down. One option to fix this I think is to revert temporarily the hugo migration.

https://github.com/maplibre/maplibre-gl-js-docs/issues/160

### CODE REVIEW

**Comment by wipfli** [comment]
Probably easier would be to push to a new branch like gh-pages2 an roll back historuly there ...

**Review by nyurik — APPROVED** [review]

**Comment by maxammann** [comment]
Did you try to rerun the deployment of the MapLibre docs? I'm quite sure this is a GitHub deployment/action/pages issue.

**Comment by wipfli** [comment]
Good idea to try rebuild gh-pages. I triggered it on the docs repo. Lets see...

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-js-docs/issues/160

**Pull request closed without merging**
