### PR TITLE
Add twitter meta tags

### PR DESCRIPTION
**Pull request by birkskyum**
Add cover image prepared by Duje (GL JS v3) to twitter cards - it says MapLibre all over in Title and Description, and Post text, so it shouldn't be too confusion that it's us.

Closes https://github.com/maplibre/maplibre/issues/285

### CODE REVIEW

**Review by wipfli — APPROVED** [review]
Cool, thanks!

**Comment by birkskyum** [comment]
Progres... 

Screenshot 2023-05-23 at 21 44 37

**Comment by wipfli** [comment]
Aha!

**Comment by wipfli** [comment]
Strange, because for me it still does not work... https://dnschecker.org/open-graph-preview-generate-metatags.php?query=https%3A%2F%2Fmaplibre.org%2Fnews%2F2023-05-23-maplibre-gl-js-v3%2F

**Comment by wipfli** [comment]
This is the header I get in my browser:

```html
<head>
    <meta charset=utf-8>
    <meta http-equiv=x-ua-compatible content="IE=edge">
    <meta name=viewport content="width=device-width,initial-scale=1">
    <meta name=author content="map[]">
    <meta name=keywords content>
    <meta name=description
        content="MapLibre GL JS v3 - Improvements to WebGL2, Terrain3D, Color spaces, Performance and more!">
    <meta name=theme-color content="#fff">
    <meta property="og:image" content="/img/share-image.png">
    <meta property="og:image:width" content="1024">
    <meta property="og:image:height" content="512">
    <meta property="og:image:alt" content="MapLibre">
    <meta property="og:title" content="MapLibre GL JS v3">
    <meta property="og:description"
        content="MapLibre GL JS v3 - Improvements to WebGL2, Terrain3D, Color spaces, Performance and more!">
    <meta property="og:url" content="https://maplibre.org/news/2023-05-23-maplibre-gl-js-v3/">
    <meta name=twitter:card content="summary_large_image">
    <meta name=twitter:site content="@maplibre">
    <meta name=twitter:creator content="@maplibre">
    <meta name=twitter:title content="MapLibre GL JS v3">
    <meta name=twitter:description
        content="MapLibre GL JS v3 - Improvements to WebGL2, Terrain3D, Color spaces, Performance and more!">
    <meta name=twitter:image:src content="/img/share-image.png">
    <meta name=twitter:image:alt content="MapLibre">
    <link rel=me href=https://mastodon.social/@maplibre>
    <link rel=stylesheet href=/style.min.b2fa5a3420d6a93fecb5136c6c3ac59ef7c2d483c57584228b770e58b0dc799f.css>
    <link rel=stylesheet href=/mapbox-gl.5d216becb39cb8484b4c28f1103286616af26e7c6f9846ead6f55e6f368e7464.css>
    <script type=text/javascript src=/main.f6b38f8cf56bdcb46ba569d3b5dfa8d46f7a42d9d4ccf261c1b92a0394a20a2a.js></script>
    <title>MapLibre GL JS v3 |
        MapLibre</title>
</head>
```

**Comment by birkskyum** [comment]
Think it works now

**Pull request merged**
